apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::429520377258:role/UdacityFlaskDeployCBKubectlRole
      username: build    
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::429520377258:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-7PE6RJ54OLVT
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-18T18:09:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1296"
  uid: f912e68d-04eb-473a-a50d-6c853c07c6a5
